### ISSUE TITLE
Not mobile-first

### ISSUE THREAD

**Issue by garrettw** [MartijnCuppens/rfs#4]
What are your thoughts on changing the algorithm to be mobile-first (i.e. take font size on mobile as the argument and use min-width in the output)?
Ultimately the effect could be the same, but readability could be better for those accustomed to writing for mobile-first (of which there are many).

Or another option might be to just add a mixin for mobile-first sizing.

See: _[Precise control over responsive typography](https://madebymike.com.au/writing/precise-control-responsive-typography/)_

**Comment by MartijnCuppens** [comment]
Hi @garrettw,

The main reason it wasn't designed mobile first is that browsers without `vw`-unit support will correctly render there font-size.

If we use the mobile-first approach, we get this:
SCSS:
```scss
.title {
  @include rfs(62);
}
```

CSS:
```css
.title {
  font-size: calc(23.6px + 3.2vw);
}

@media (min-width: 1200px) {
  .title {
    font-size: 62px;
  }
}
```
For older browsers with a screen-width smaller as `1200px` the font-size will not be set.

However it might be interesting to add an option like `$rfs-mobile-first` (default value: false) which switches to mobile first rendering?

**Comment by MartijnCuppens** [comment]
@garrettw, I just added an option for mobile-first rendering, you can enable it by setting `$rfs-mobile-first` true.

**Comment by garrettw** [comment]
The article I linked above does it in a slightly different way. Thoughts?
```css
.title {
  font-size: 12px; /* base, mobile-first size */
}

@media (min-width: 400px) {
  .title {
    /* scaling size for viewports between 400px-800px */
    font-size: calc( 12px + (24 - 12) * ( (100vw - 400px) / ( 800 - 400) ));
  }
}

@media (min-width: 800px) {
  .title {
    font-size: 24px; /* largest size for viewports wider than 800px */
  }
}
```
