### ISSUE TITLE
2 dimensional media-queries and vmin-units

### ISSUE THREAD

**Issue by MartijnCuppens** [MartijnCuppens/rfs#5]
At this moment, the font size only rescales based on the screen width, not the screen height. A side-effect of this is that font-sizes of portrait and landscape can differ a lot. To prevent this, I'll add an option to change the rendering like this:

SCSS:
```scss
.title {
  @include rfs(62);
}
```

CSS:
```css
.title {
  font-size: 62px;
}

@media (max-width: 1200px), (max-height: 1200px) {
  .title {
    font-size: calc(23.6px + 3.2vmin);
  }
}
```

And with `$rfs-mobile-first` set to `true`:
```css
.title {
  font-size: calc(23.6px + 3.2vmin);
}

@media (min-width: 1200px) and (min-height: 1200px) {
  .title {
    font-size: 62px;
  }
}
```

This option (`$rfs-two-dimensional`) will not be enabled by default (yet).
